[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd packages/db && bunx prisma generate --schema ../../prisma/schema.prisma"
]

[start]
cmd = "bun run --filter=api dev"
